### ISSUE TITLE
Gallery not working on Federated Shares: 403

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/gallery#411] opened 2018-03-21 09:26 UTC
On both - federated share sending and receiving - Nextclouds:
NC 13.0.1
Gallery 18.0
Federation 1.3.0

On the receiving NC: 
* Navigate in Files app to the received federated share folder
* Switch to Gallery mode

Error: 
Album cannot be shown
The owner has placed a restriction or the storage location is unavailable (403)

![image](https://user-images.githubusercontent.com/3857906/37702209-1d4530d2-2cf2-11e8-97d8-c0de7312ac9c.png)

**Comment by skjnldsv** [comment] 2019-09-03 18:19
Duplicate of #128

**Closed by skjnldsv** 2019-09-03 18:19 UTC
