### ISSUE TITLE
13.0.0 RC1 Gallery while logged contains fewer photos than the same gallery using the share link

### ISSUE THREAD

**Issue by rubrik** [nextcloud/gallery#364] opened 2018-01-15 18:44 UTC
(system info in https://github.com/nextcloud/server/issues/7841)

When I am logged into Nextcloud, and view a directory of images using Files, I see everything that is there.
If I switch to grid view/Gallery, I see far fewer photos, like it is paginating but not giving me the option to go to the next page.

The same folder is shared using a share link, there all photos are always visible.

I don't remember having this problem in 12

**Comment by rubrik** [comment] 2018-01-15 18:44
@ koarlmichael can reproduce this problem

**Comment by oparoz** [comment] 2018-01-15 21:08
If images are on external storage, managed by the files_external app, then they won't show in Gallery.
IF that's not the problem, then there must be something in the browser logs, showing that the streaming of thumbnails has been interrupted.

**Comment by rubrik** [comment] 2018-01-15 22:09
The files are on external storage (actually it's a local filesystem, but accessed through the external storage app).

The first lot of files (not all of them) are showing - should they not be?

**Comment by koarlmichael** [comment] 2018-01-16 07:14
The bug has been since the update from NC 12.0.4 to NC 13 RC1. I can see all the pictures in the file view. When I click on the gallery view, only about 55 to 60 pictures appear on the Macbook Air 13 inch, depending on the album. When I go sorting, no matter by date or alphabetically, other pictures of the album appear, but no more than about 55 to 60.
I tested the same on a larger 23 inch monitor. There suddenly appear more pictures, about 80 - 85. albums that do not have so many pictures and on the smaller screen of the Macbooks were not completely displayed, you can see completely on the bigger screen. 

Location is local, tested on Firefox 57 and Chrome 63. No error message in the logs. 
If you share the gallery via a link you can suddenly see all the pictures.

**Comment by oparoz** [comment] 2018-01-17 15:14
Some recent changes in the CSS or JS seem to have killed the autoloading of thumbnails

**Comment by danxuliu** [comment] 2018-01-17 16:25
The regression was introduced in #336, specifically in commit https://github.com/nextcloud/gallery/pull/336/commits/55dd75045d9261cbe77d41a5a0789749bd4bd3d3

**Comment by rullzer** [comment] 2018-01-18 10:48
@pixelipo can you have a look?

**Comment by pixelipo** [comment] 2018-01-18 12:45
I wasn't able to reproduce this bug (seeing all the images in both cases, in various screen resolutions), but I did see a double vertical scroller, so I'm suspecting that's what's causing this issue. I've fixed the relative heights in #366 - please test whether that PR fixes this issue.

**Comment by danxuliu** [comment] 2018-01-18 13:13
>  I did see a double vertical scrollbar, so I'm suspecting that's what's causing this issue.

I would say that you had a cache issue ;-) The double vertical scrollbar was in fact fixed in https://github.com/nextcloud/gallery/pull/336, specifically in commit https://github.com/nextcloud/gallery/pull/336/commits/a418fadac94b5b4d377696914a8de7f159d4d422, which happens to be the parent commit of the offending one.

#366 does fix the scrolling... but also breaks again the controls ;-) Exactly the opposite of https://github.com/nextcloud/gallery/commit/55dd75045d9261cbe77d41a5a0789749bd4bd3d3

**Comment by pixelipo** [comment] 2018-01-18 13:18
Thanks for testing @danxuliu - I added `position: relative` to revert my earlier `#controls` fix. Please check now

**Closed** 2018-01-18 15:28 UTC
Labels: 3. to review, bug, regression

**Comment by oparoz** [comment] 2018-01-18 16:01
Thanks you all for reporting and fixing the issue.
This should be delivered as part of 13RC2

**Comment by rubrik** [comment] 2018-01-19 17:03
Thanks WFM with forced refresh in browser.
