### ISSUE TITLE
Upload button does not work

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/gallery#200] opened 2017-02-04 07:01 UTC
### Steps to reproduce
1. Open the gallery
2. Click on the + sign
3. Try to upload a picture

### Expected behaviour
Picture should be uploaded

### Actual behaviour
Nothing happens

### More information
https://help.nextcloud.com/t/nc-11-gallery-16-0-0-no-picture-upload-possible/

<strike>This issue is already filed as bug but posted in the wrong category.

https://github.com/nextcloud/server/issues/3229

Can an admin move it to here please?
Thank you.</strike>

**Comment by oparoz** [comment] 2017-02-04 10:46
We can't move an issue across projects, so just copy/paste the OP from server to replace the OP here. Thanks!

**Comment by Sanookmakmak** [comment] 2017-02-06 11:48
done @oparoz

**Comment by oparoz** [comment] 2017-02-10 09:12
Drag and drop is also broken. 

@rullzer Any idea what has changed in the server in 11 regarding uploads?

**Comment by JaredBoone** [comment] 2017-02-13 22:13
When this is fixed please consider backporting to the stable11 branch.

**Comment by oparoz** [comment] 2017-02-13 22:21
The first step is for people to post logs so that we can get a hint of what's happening.

**Comment by JaredBoone** [comment] 2017-02-13 22:43
I have reproduced this in Windows 7 with Chrome 56.0.2924.87 and Firefox 51.0.1. I have also reproduce it in OS X Yosemite 10.10.5 with Chrome 56.0.2924.87 and Firefox 51.0.1.

Here are the steps to reproduce:
* Open Gallery app
* Click on upload "+" icon
* Click on the "Upload" menu item
* Select an image file to upload from my local file system
* Click the "Open" button
* Observe that the file selector dialog closes, but nothing else happens and no file is uploaded. In the browser web developer tools, no network requests are sent to the server, no javascript console log or error message appears. 

How can I help?

**Comment by oparoz** [comment] 2017-02-13 23:22
PLease add  'debug' => true,` to your config.php to see if it helps generate browser logs.

**Comment by JaredBoone** [comment] 2017-02-13 23:39
I set 'debug' to true in config.php but I don't see any additional output in the browser logs. 

I also modified apps/files/js/file-upload.js - I set "_trace" to true, but I see no console output from the "log" function in that file.

**Comment by JaredBoone** [comment] 2017-02-13 23:46
Uploading this same file works fine when I use the "Files" app. Also, when using the Files app, I see multiple lines of browser console log output from file-upload.js (after setting _trace set to true).

**Comment by oparoz** [comment] 2017-02-14 00:42
Basically, this commit broke everything:
https://github.com/nextcloud/server/commit/59c5be1cc572793a8d50e87ab589e1cc4cf2ed12

So someone needs to match the changes or we need to remove the functionality.

**Comment by Sanookmakmak** [comment] 2017-02-16 17:48
> we need to remove the functionality.

Why does the files app can upload the file without any problems and the gallery app can't?

**Comment by oparoz** [comment] 2017-02-16 20:09
>Why does the files app can upload the file without any problems and the gallery app can't?

Because there isn't a shared component apps can use to make it possible to perform classic files operations such as upload, move, copy. Each app has to implement it. In order to not have to write too much code which is unrelated to Files, I re-used the base libraries, but the way it works has changed last year, so Gallery needs to get the same changes.

**Comment by Sanookmakmak** [comment] 2017-02-17 15:58
> Because there isn't a shared component apps can use to make it possible to perform classic files operations such as upload, move, copy. Each app has to implement it.

So every developer has to invent the wheel again. Wouldn't that be a nice improvement for a new Nextcloud version?
;-)

**Comment by jasonbayton** [comment] 2017-02-28 12:48
@Sanookmakmak interestingly a comment a user Stuart on the forum keeps bringing up. Shared intents and whatnot.

It's a grand idea.

**Comment by hudriwu** [comment] 2017-03-02 11:33
any news? does an update to 11.0.2 solve the problem?

**Comment by oparoz** [comment] 2017-03-02 12:36
No, this will be in NC 12 and backported to 11.0.3

**Comment by oparoz** [comment] 2017-04-16 21:53
Fix is in #238

**Closed** 2017-04-18 07:20 UTC
Labels: backport-request, bug, high, Regression
