### ISSUE TITLE
The download button is gone after Nextcloud 16 update

### ISSUE THREAD

**Issue by pervin11111** [nextcloud/gallery#517] opened 2019-05-17 23:23 UTC
I updated my server to the latest Nextloud 16 ( then to 16.0.1 a couple of days later ). Noticed the gallery app is missing the download button, which was there through Nextcloud 15. But when I enable the gallery from the top left corner, the download button is there as it should be. Is it a bug? 
Thank you!

**Normal file view ( no download button ):**
![no download button](https://user-images.githubusercontent.com/38087921/57960819-01815400-78d9-11e9-84c1-fddb120ec448.jpg)

**Gallery mode ( download button works ):**
![download button](https://user-images.githubusercontent.com/38087921/57960841-19f16e80-78d9-11e9-8e3e-cc747f8ebccc.jpg)

**Comment by viesulas** [comment] 2019-05-30 18:40
Maybe it's not a bug - try to disable no button Viewer app to enable Gallery app in Files mode.

**Comment by pervin11111** [comment] 2019-05-30 19:34
> Maybe it's not a bug - try to disable no button Viewer app to enable Gallery app in Files mode.

Can confirm it works, would not have guessed that hehe. Thank you so much!

**Comment by skjnldsv** [comment] 2019-09-03 18:04
Duplicate of https://github.com/nextcloud/viewer/issues/88

**Closed by skjnldsv** 2019-09-03 18:04 UTC
