### ISSUE TITLE
Image preview generation on opening folders gets aborted

### ISSUE THREAD

**Issue by Marco-Jacobs** [nextcloud/gallery#507] opened 2019-03-16 20:59 UTC
# Bug report

The preview generagion gets aborted on new folders after the first 4 or sometimes 5 Images.
This problems exist as far as i could reproduce it on all NC 15.x Versions. 
With 14.x the pictures gets generated one after another.

## Steps to reproduce

If you add a new folder with for example 10 images inside and open the folder in gallery view  the 4 images for the folder icon gets generated. If you now open the folder, NC only shows these 4 pictures and the working circle disapears afer a few seconds.
And 30 min later is still not a single picture more generated.

![image](https://user-images.githubusercontent.com/12143264/54481292-31f23680-4833-11e9-8a13-489ca7357f1d.png)

In this situation a reload of the folder doesnt chance anything.

If you now switch to the file list, all missing prewievs will be generated.

![image](https://user-images.githubusercontent.com/12143264/54481302-40d8e900-4833-11e9-94de-b7edd3595ef7.png)

After that you can go back to the gallery view and all pictures will be shown.

![image](https://user-images.githubusercontent.com/12143264/54481308-49c9ba80-4833-11e9-986e-b42468d3e2fe.png)

## Expected behaviour

After the first 4 images all other image previews will be generated.
The same way as it is in the file list view and in NC 14.x. 

## Actual behaviour

The preview generation gets aborted.

## Server configuration

**Operating system**: Ubuntu 18.04 LTS 64bit
**Web server:** Apache/2.4.29
**Database:** MySQL 5.7.25
**PHP version:** 7.2.15

### Nextcloud configuration

**Nextcloud version:** 15.0.5

**Updated from an older installation or fresh install:** updates every version since the first 15.x version

## Client configuration

**Browser:**
Google Chrome 72.0.3626
IE 11.648

**Operating system:** 
Windows 10
Ubuntu 18.10

**Are you a developer willing to implement this feature?**: developer yes but not much knowledge about the NC code

**Comment by Marco-Jacobs** [comment] 2019-03-19 07:58
## Additional Information

It seems, this problem doesn´t exist if the folder contains jpg files.
In my example the folder contains dng files only.
Maybe this is the key to solve it.

**Comment by godfuture** [comment] 2019-03-25 12:11
I have the same issue with the thumbs in grid view. Rarely it finishes well, mostly it loads incomplete.
![PreviewNotloading](https://user-images.githubusercontent.com/4669278/54917731-bd875980-4efc-11e9-94e8-c403c147131b.jpg)

Nextcloud - 15.0.5
Gallery - 18.2.0

**Comment by skjnldsv** [comment] 2019-09-03 17:56
Duplicate of #524

**Closed by skjnldsv** 2019-09-03 17:56 UTC
