### ISSUE TITLE
Controls for next/previous and autoplay or navigation via keyboard don't work

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/gallery#275] opened 2017-05-22 16:11 UTC
Check it out on https://cloud.nextcloud.com/apps/gallery/s/0WDHAi9p5n0JSew# 

- Previous/next don't work neither via buttons nor arrow keys
- Neither does the autoplay/slideshow mode

cc @nextcloud/gallery

**Comment by oparoz** [comment] 2017-05-23 15:25
Duplicate of https://github.com/nextcloud/gallery/issues/270

**Closed by oparoz** 2017-05-23 15:25 UTC
Labels: duplicate
