### ISSUE TITLE
File list refreshes after closing Gallery slideshow

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#71] opened 2016-09-04 11:28 UTC
_From @jancborchardt on September 8, 2015 13:22_

1. Open an image with the Gallery slideshow / detail view
2. Close it again

Expected:
You are able to seamlessly browse your pics again.

What actually happens:
The whole file list is very visibly reloaded. That’s confusing and rips you out of the flow.

@oparoz @schiesbn @PVince81 @MorrisJobke what can we do here? Same is true for the text editor cc @tomneedham

_Copied from original issue: owncloud/gallery#313_

**Comment by MorrisJobke** [comment] 2016-09-05 07:29
Duplicate of #72

**Closed by MorrisJobke** 2016-09-05 07:29 UTC
Labels: blocked by core, bug, design, feature:slideshow, ready

**Comment by oparoz** [comment] 2016-09-05 10:04
Thanks :)
