### ISSUE TITLE
Provide option to select images in gallery view

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/gallery#506] opened 2019-03-16 09:57 UTC
![grafik](https://user-images.githubusercontent.com/24833757/54473589-1d358480-47da-11e9-907b-434cde250854.png)

See also: https://help.nextcloud.com/t/gallery-how-to-select-images/32162

**Comment by skjnldsv** [comment] 2019-09-04 06:11
Duplicate of #328

**Closed by skjnldsv** 2019-09-04 06:11 UTC
