### ISSUE TITLE
Next/prev/slide show button don't work in shared link gallery

### ISSUE THREAD

**Issue by vrs01** [nextcloud/gallery#292] opened 2017-07-06 12:27 UTC
### Steps to reproduce

1. Create a shared link of a folder containing images
2. Open the link
3. Switch the view to gallery
4. Open any image
5. Press prev / next or slideshow

### Expected behaviour

A different image should appear when I hit the buttons.

### Actual behaviour

Nothing.

It works fine when clicking on the arrows in the gallery view at the nextcloud interface without using a shared link. It is also working when opening the slideshow from the file list view of a shared link.

### Server configuration
**Operating system**: Linux raspi-nextcloud 4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l

**Web server:** Apache/2.4.25 (Raspbian) (apache2handler)

**Database:** mysql 5.6.30

**PHP version:** 7.0.19-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_notifications: 1.0.0
 - audioplayer: 2.0.2
 - bookmarks: 0.10.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - circles: 0.11.0
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.1
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.0.2
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - passman: 2.1.2
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - admin_audit
 - encryption
 - registration
 - richdocuments
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oci1xaaaqe9q",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.105",
        "nextcloudvrs.firewall-gateway.com"
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/192.168.1.103",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": 
    "mail_domain": "posteo.de",
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "posteo.de",
    "mail_smtpauth": 1,
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "app.mail.imaplog.enabled": true,
    "app.mail.smtplog.enabled": true
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by xraMsamohT** [comment] 2017-07-26 21:37
Previous
```
TypeError: Gallery.Share is undefined  slideshowcontrols.js:372:4
	_previous https://domain.tld/apps/gallery/js/slideshowcontrols.js:372:4
	init/makeCallBack</< https://domain.tld/apps/gallery/js/slideshowcontrols.js:55:6
	bound  self-hosted:913:17
	dispatch https://domain.tld/core/vendor/core.js:3:6414
	add/r.handle https://domain.tld/core/vendor/core.js:3:3224
```
Next
```
TypeError: Gallery.Share is undefined  slideshowcontrols.js:353:4
	_next https://domain.tld/apps/gallery/js/slideshowcontrols.js:353:4
	init/makeCallBack</< https://domain.tld/apps/gallery/js/slideshowcontrols.js:55:6
	bound  self-hosted:913:17
	dispatch https://domain.tld/core/vendor/core.js:3:6414
	add/r.handle https://domain.tld/core/vendor/core.js:3:3224
```
Play
```
TypeError: Gallery.Share is undefined slideshowcontrols.js:353:4
	_next https://domain.tld/apps/gallery/js/slideshowcontrols.js:353:4
	bound _next self-hosted:911:17
```
- - -
The slideshow – also on a shared album/gallery – is a main function of this app, imho.

**Comment by xraMsamohT** [comment] 2017-08-01 15:55
Duplicate of #270

**Closed** 2017-08-02 09:07 UTC
