### ISSUE TITLE
Sharing gallery image downloads the image instead of displaying in the browser

### ISSUE THREAD

**Issue by weikai** [nextcloud/gallery#500] opened 2019-02-17 17:15 UTC
The sharing link generated in gallery downloads the image instead of displaying.  Can we fix it so the users can open the image in the browser using the shared link?  It prompt for download location when clicked right now.

# Bug report

## Steps to reproduce

1. View the images in gallery
2. Open one of the images and click on the share link
3. The shared link generated downloads the image not open in the browsers

## Expected behaviour
Open the shared image in the browser
## Actual behaviour
Prompts for download location.

## Server configuration
**Operating system**:
Uuntu 18.04
**Web server:**
Apache 2
**Database:**
Mysql
**PHP version:**
PHP 7.2
### Nextcloud configuration

**Nextcloud version:** (see admin page or version.php)
15.0.4
**Updated from an older installation or fresh install:**
Fresh installation
**List of activated apps:**

<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_sharing: 1.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - lookup_server_connector: 1.3.0
  - oauth2: 1.3.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - sharebymail: 1.5.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap

```

</details>

**Nextcloud configuration:**

<details>
<summary>Config.php</summary>
  
```
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.weikai.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }

```

</details>

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
No
**Are you using encryption:** yes/no
No
**Are you using custom gallery.cnf config files:** yes/no
no
### Web server error log

<details>
<summary>Web server error log</summary>

```
no error log
```
</details>

### Nextcloud log

<details>
<summary>Nextcloud log</summary>

```
no error log
```
</details>

## Client configuration

**Browser:**
Chrome
**Operating system:**
Windows 10
### Browser log

<details>
<summary>Browser log</summary>

```
No error log
```

</details>

# Feature request

**User type**: Logged-in or public user
public user

**User level**: Beginners, intermediate or advanced

## Sponsorship

**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by skjnldsv** [comment] 2019-09-04 09:59
Unrelated to gallery. 
Duplicate of #466

**Closed by skjnldsv** 2019-09-04 09:59 UTC
